fix uppercase problem

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,15 +25,12 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
-
       - name: Install Node.js 
         uses: actions/setup-node@v3
         with:
           node-version: 24
-
       - name: Install Dependencies
         run: npm install
-
       - name: Run Tests
         run: npm test
 
@@ -43,18 +40,15 @@ jobs:
     permissions:
       contents: read
       packages: write
-      
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
-
       - name: Log in to the Container registry
         uses: docker/login-action@v2
         with:
           registry: ${{ env.REGISTRY }}
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
-
       - name: Extract metadata (tags, labels) for Docker
         id: meta
         uses: docker/metadata-action@v4
@@ -63,7 +57,6 @@ jobs:
           tags: |
             type=raw,value=latest
             type=sha
-
       - name: Build and push Docker image
         uses: docker/build-push-action@v4
         with:
@@ -72,7 +65,6 @@ jobs:
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
 
-  
   deploy:
     needs: build-and-push
     runs-on: ubuntu-latest
@@ -84,13 +76,24 @@ jobs:
           username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
-            mkdir -p ~/Shortener
-            cd ~/Shortener
+            mkdir -p ~/Shortener/code
+            cd ~/Shortener/code
             
             
+            REPO_NAME="${{ github.repository }}"
+            IMAGE_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
+            
+           
             echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
 
-           
-            docker pull ghcr.io/${{ github.repository }}:latest
-            docker compose down
+            echo "Pulling image: ghcr.io/$IMAGE_NAME:latest"
+            docker pull ghcr.io/$IMAGE_NAME:latest
+            
+            
+            if [ ! -f docker-compose.yml ]; then
+              echo "Error: docker-compose.yml not found in ~/Shortener/code!"
+              exit 1
+            fi
+
+            docker compose down || true
             docker compose up -d
